name: smartshield-app
services:
  # Backend API
  - name: backend
    source_dir: backend
    github:
      repo: your-username/smartshield
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 4000
    envs:
      - key: NODE_ENV
        value: production
      - key: USE_SUPABASE
        value: "true"
      - key: PORT
        value: "4000"

  # Dashboard Frontend
  - name: dashboard
    source_dir: dashboard
    github:
      repo: your-username/smartshield
      branch: main
    run_command: npm run build && npm run preview
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    envs:
      - key: REACT_APP_API_URL
        value: ${backend.PUBLIC_URL}

  # Website Landing Page
  - name: website
    source_dir: website
    github:
      repo: your-username/smartshield
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080

databases:
  - name: smartshield-db
    engine: PG
    version: "15"
    size: db-s-dev-database
